/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases.ventanas;

import clases.ManipulaBD;
import clases.Productos;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author roodi
 */
public class ConsultasProductos extends javax.swing.JFrame
{
    
    private int indice;
    private ArrayList<Productos> lista;

    /**
     * Creates new form ConsultasProductos
     */
    public ConsultasProductos()
    {
        initComponents();
        llenarTabla();
    }
    
    private void llenarTabla()
    {
        lista = ManipulaBD.ConsultaProductos("id!=", "-1");
        if (lista != null)
        {
            int tamaño = lista.size();
            Object matriz[][] = new Object[tamaño][8];
            for (int i = 0; i < lista.size(); i++)
            {
                matriz[i][0] = lista.get(i).getId();
                matriz[i][1] = lista.get(i).getId_Proveedores();
                matriz[i][2] = lista.get(i).getNombre();
                matriz[i][3] = lista.get(i).getCantidad();
                matriz[i][4] = lista.get(i).getPrecio();
                matriz[i][5] = lista.get(i).getPeso();
                matriz[i][6] = lista.get(i).getTipoProducto();
                matriz[i][7] = lista.get(i).isEstatus();
            }
            
            Tproductos.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]
            {
                "Id", "Proveedor", "Nombre", "Cantidad", "Precio", "Peso", "TipoProducto", "Estatus"
            })
            {
                Class[] types = new Class[]
                {
                    Integer.class, Integer.class, String.class, Integer.class, Double.class, Double.class, Integer.class, Boolean.class
                };
                
                public Class getColumnClass(int columnIndex)
                {
                    return types[columnIndex];
                }
                
                @Override
                public boolean isCellEditable(int row, int column)
                {
                    if (column != 0)
                    {
                        return true;
                    } else
                    {
                        return false;
                    }
                }
                
            }
            );
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tproductos = new javax.swing.JTable();
        cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBajas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Id", "Proveedor", "Nombre", "Cantidad", "Precio", "Peso", "Tipo de producto", "Estatus"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        Tproductos.setColumnSelectionAllowed(true);
        Tproductos.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                TproductosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Tproductos);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Productos");

        btnBajas.setText("Bajas");
        btnBajas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBajasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(335, 335, 335))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBajas))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(btnBajas))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        switch (Login.getUsu().get(0).getPuesto())
        {
            case "Admin":
                new Admin().setVisible(true);
                this.setVisible(false);
                break;
            case "Empleado":
                new Empleado().setVisible(true);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_cancelarActionPerformed

    private void TproductosKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TproductosKeyReleased
    {//GEN-HEADEREND:event_TproductosKeyReleased
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            indice = Tproductos.getSelectedRow();
            int id = lista.get(indice).getId();
            System.out.println("id===" + id);
            int id_po = (int) Tproductos.getValueAt(indice, 1);
            String nom = (String) Tproductos.getValueAt(indice, 2);
            int canti = (int) Tproductos.getValueAt(indice, 3);
            double pre = (double) Tproductos.getValueAt(indice, 4);
            double pes = (double) Tproductos.getValueAt(indice, 5);
            int tipo = (int) Tproductos.getValueAt(indice, 6);
            
            ManipulaBD.ModificarProductos(id, "id_proveedores", "" + id_po + "");
            ManipulaBD.ModificarProductos(id, "nombre", "'" + nom + "'");
            ManipulaBD.ModificarProductos(id, "cantidad", "" + canti + "");
            ManipulaBD.ModificarProductos(id, "precio", "" + pre + "");
            ManipulaBD.ModificarProductos(id, "peso", "" + pes + "");
            ManipulaBD.ModificarProductos(id, "tipoProducto", "" + tipo + "");
        }

    }//GEN-LAST:event_TproductosKeyReleased

    private void btnBajasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBajasActionPerformed
    {//GEN-HEADEREND:event_btnBajasActionPerformed
        for (int i = 0; i < lista.size(); i++)
        {
            boolean est = (boolean) Tproductos.getValueAt(i, 7);
            String esta = String.valueOf(est);
            ManipulaBD.ModificarProductos(lista.get(i).getId(), "estatus", "'" + esta + "'");
        }
    }//GEN-LAST:event_btnBajasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ConsultasProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ConsultasProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ConsultasProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ConsultasProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ConsultasProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tproductos;
    private javax.swing.JButton btnBajas;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
